sudo: false
language: node_js
node_js:
    - stable
    - '0.12'
env:
    - NODE_ENV=development
install:
    - npm install
    # Install specific gulp-sass version.
    # Compromise between getting builds working for more recent NodeJS versions
    - npm uninstall gulp-sass
    - npm install gulp-sass@2
    - cp _config/task.sass.js test/mock-project/_config/task.sass.js
    - cp package.json test/mock-project/package.json
    - cd test/mock-project
    - npm install
    - npm install gulp
    - cd ../..
    - npm install mocha -g
    - npm install gulp-cli -g
script:
    - mocha
cache:
  directories:
    - node_modules
    - test/mock-project/node_modules
git:
  depth: 1
